### ISSUE TITLE
Search episodes with HTTP instead of HTTPS

### ISSUE THREAD

**Issue by vtcosta** [SickRage/sickrage-issues#716]
I've installed SickRage on OpenWrt (Attitude Adjustment 12.09), and I've been getting the following error when trying to search for episodes:
```
2016-01-30 18:36:51 WARNING  SEARCHQUEUE-MANUAL-269586 :: [ThePirateBay] :: Connection error to getURL https://thepiratebay.se/s/?q=Brooklyn+Nine-Nine+S03E12&orderby=7&category=200&type=search&page=0 Error: u'error [Errno 1] _ssl.c:504: error:14077438:lib(20):func(119):reason(1080)' [f568d15]
```
It used to work a long time ago, probably because it was using HTTP, but I don't know exactly when their feed (or your code) switched to HTTPS. I've tried to install SSL modules, but couldn't managed to do that in my version of OpenWrt.

Anyhow, this same URL works with non secure HTTP. Is there a setting to avoid using HTTPS, and instead fallback to HTTP??

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@vtcosta There should be a custom url field under the TPB settings, just use http there.
To prevent ssl issues we recommend openssl v 1.01e minimum, and python v2.7.10 if possible.

**Comment by vtcosta** [comment]
@SickRage2, I guess that my report fulfilled all your requirements. The log reports the commit (f568d15), I've told that I was using OpenWrt, I've told what happened, and that there was a SSL problem with my OS. There was no need for debugging, since I've nailed down the root cause of this issue.

@neoatomic, thanks a lot for that information. Never seen that setting. I've just tried that, and logs shows that it is using HTTP:
```
2016-01-30 20:24:27 WARNING  SEARCHQUEUE-MANUAL-269586 :: [ThePirateBay] :: Connection error to getURL http://thepiratebay.se:80/s/?q=Brooklyn+Nine-Nine+S03E12&orderby=7&category=200&type=search&page=0 Error: u'error [Errno 1] _ssl.c:504: error:14077438:lib(20):func(119):reason(1080)' [f568d15]
```
Unfortunately, I've noticed that HTTP requests are redirected to HTTPS. That's not SickRage fault, torrent sites are doing that.

Looks like OpenWrt (Attitude Adjustment 12.09) has Python 2.7.3 and OpenSSL 1.0.1e. Newest version (Chaos Calmer 15.05) has Python 2.7.9 and OpenSSL 1.0.2f. I just don't want to upgrade OpenWrt because it has to be a fresh install.

I will look further into this SSL issue with OpenWrt 12.09. If anyone has any info about this issue with OpenWrt 12.09, please, share it with us.

**Comment by neoatomic** [comment]
@vtcosta Sickrage2 is a bot/auto message, so don't worry responding. :P 

You should be able to get it working with python 2.7.3 also. But you will have to update some dependencies of python. So if that's possible, then it should solve the SSL issues.

btw, wasn't even aware that sickrage would run on Openwrt, thats pretty cool. :+1:  
Is there some setup guide.? i'm sure more users would like to try that.

**Comment by vtcosta** [comment]
I've been using SickBeard since 2013 without a single issue. There is nothing special in installing it in OpenWrt. All you have to do is install python and pip, install SickBeard's dependencies with pip (Cheetah, etc), clone SickBeard repository and run it.

Below is my pip list if anyone needs it (there maybe things not related to SickRage):
```
Cheetah (2.4.4)
Fabric (1.8.3)
Markdown (2.4)
paramiko (1.12.3)
pexpect (2.3)
pip (1.5.4)
setuptools (3.1)
wsgiref (0.1.2)
```

But then SickBeard has stopped development, so I moved to SickRage. A few months later I started having this issue with HTTPS.

Anyhow, I installed OpenWrt's version of pyOpenSSL (0.10), and the my error changed to:
```
'_socketobject' object has no attribute 'set_tlsext_host_name'
```

I went to pyOpenSSL documentation and saw that `set_tlsext_host_name` is available since 0.13.

So I uninstalled it, and tried to install latest version (0.15.1) with pip, but I got the following error:
```
unable to execute ccache_cc: No such file or directory
```
I even tried installing version 0.13, but got the same error. I am not a Linux expert so I don't how to resolve this problem. I've seen that ccache_cc is related to gcc compiler, but I have no idea how to install it in OpenWrt.

If anyone has a clue how to do it, please share with us.

In the meantime, I will continue to download episodes manually. Everything else works fine in SickRage (updating episode information, showing episodes aired but now downloaded, post processing, and plex notifications).
